# based on https://github.com/RecapTime/verify/blob/main/.github/workflows/dependabot.yml
name: Fix borked Yarn lockfiles

on:
  push:
    branches: [dependabot/npm_and_yarn/**]
  issue_comment:
    types: [created]

jobs:
  # We cannot push stuff on pull_request, especially GitHub just think PRs from Dependabot treats the same as PRs from forks, which we cannot use our PAT.
  fix-on-push:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "16"
      - name: Autofix lockfile
        run: |
          # change directory
          cd .`git log -1 --pretty=%s | awk '{ print $8 }'`
          # restore yarn.lock from the previous commit
          git checkout HEAD^ -- yarn.lock
          # if package.json was not updated, upgrade the dependency
          git diff --name-only HEAD^ HEAD | grep -q 'package.json' || yarn up `git log -1 --pretty=%s | awk '{ print $2 }'`
          # restore package.json from the last commit
          git checkout HEAD -- package.json
          yarn install --no-immutable
          # deduplicate lockfile
          yarn dedupe
      - name: Config Git
        run: |
          # We use our own PAT for this, if you gonna use this, make sure to use the same secret name.
          BASIC_AUTH=$(echo -n "x-access-token:${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}" | base64)
          echo "::add-mask::$BASIC_AUTH"
          git config --global user.name 'Nobody In Local'
          git config --global user.email 'june@of-sound-mind.com'
          git config --local http.$GITHUB_SERVER_URL/.extraheader "AUTHORIZATION: basic $BASIC_AUTH"
      - name: Commit changes
        run: |
          cd .`git log -1 --pretty=%s | awk '{ print $8 }'`
          git add yarn.lock .yarn/cache .pnp.*
          git commit -m "chore(dependabot): fix broken Yarn lockfile" -m "Related-Issue: https://github.com/dependabot/dependabot-core/issues/1297" --signoff
          git push
  fix-on-command-usage:
    # TODO: Edit the line below via Gitpod. You probably check the GitHub Docs for help.
    if: ${{ github.event.comment.body == '@nobody-in-local fix borked lockfile' && !github.event.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout to branch
        # Attempt to checkout from HTML URL generated by the webhook payload
        run: gh pr checkout ${{github.event.html_url}}
      # TODO: Upgrade to 16.x when it reaches the Active LTS status.
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "16"
      - name: Autofix lockfile
        run: |
          # change directory
          cd .`git log -1 --pretty=%s | awk '{ print $8 }'`
          # restore yarn.lock from the previous commit
          git checkout HEAD^ -- yarn.lock
          # if package.json was not updated, upgrade the dependency
          git diff --name-only HEAD^ HEAD | grep -q 'package.json' || yarn up `git log -1 --pretty=%s | awk '{ print $2 }'`
          # restore package.json from the last commit
          git checkout HEAD -- package.json
          yarn install --no-immutable
          # deduplicate lockfile
          yarn dedupe
      - name: Config Git
        run: |
          # We use our own PAT for this, if you gonna use this, make sure to use the same secret name.
          BASIC_AUTH=$(echo -n "x-access-token:${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}" | base64)
          echo "::add-mask::$BASIC_AUTH"
          git config --global user.name 'Nobody In Local'
          git config --global user.email 'june@of-sound-mind.com'
          git config --local http.$GITHUB_SERVER_URL/.extraheader "AUTHORIZATION: basic $BASIC_AUTH"
      - name: Commit changes
        run: |
          cd .`git log -1 --pretty=%s | awk '{ print $8 }'`
          git add yarn.lock .yarn/cache .pnp.*
          git commit -m "chore(dependabot): fix broken Yarn lockfile" -m "Related-Issue: https://github.com/dependabot/dependabot-core/issues/1297" --signoff
          git push
      # TODO: Notify the user who trigger the command ONLY if fails.
